[tool.poetry]
name = "bareASGI-auth-common"
version = "1.1.0"
description = ""
authors = ["Rob Blackbourn <rob.blackbourn@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "bareasgi_auth_common", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
bareclient = "^3.0"
PyJWT = "^1.7"
PyYaml = "^5.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pylint = "^2.3"
autopep8 = "^1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
